name: noson
version: "3.9.6.snap"
summary: noson
icon: noson.png
description: |
  The essential to control music from your SONOS devices.
  It is the fast and smart controller for your SONOS devices on Ubuntu platform.
  You can browse your music library and play track, radio or internet stream on
  any zones. You can manage zone groups, queue and playlists and fully control
  the playback. Enjoy!
grade: stable
confinement: strict
base: core18

apps:
  noson:
    command: bin/noson.launcher
    plugs: [unity7, x11, wayland, opengl, home, network, network-bind, media-hub]

parts:
  noson:
    source: https://github.com/janbar/noson-app.git
    source-type: git
    source-tag: 3.9.6
    source-depth: 1
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
    build-packages:
      - build-essential
      - cmake
      - gettext
      - intltool
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - qtquickcontrols2-5-dev
      - libqt5svg5-dev
      - zlib1g-dev
      - libssl-dev
      - qml-module-qt-labs-settings
      - qml-module-qtgraphicaleffects
      - qml-module-qtqml-models2
      - qml-module-qtquick2
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-particles2
      - qml-module-qtquick-templates2
      - qml-module-qtquick-window2
      - libqt5svg5
    stage-packages:
      - libqt5qml5
      - libqt5quick5
      - libqt5quickcontrols2-5
      - qml-module-qt-labs-settings
      - qml-module-qtgraphicaleffects
      - qml-module-qtqml-models2
      - qml-module-qtquick2
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-particles2
      - qml-module-qtquick-templates2
      - qml-module-qtquick-window2
      - qttranslations5-l10n
      - libqt5svg5
      - zlib1g
      - libssl1.1
    after: [desktop-qt5]

  environment:
    source: .
    plugin: dump
    organize:
      noson.launcher: bin/noson.launcher

